-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : db
-- Généré le : ven. 21 juin 2024 à 09:09
-- Version du serveur : 8.0.37
-- Version de PHP : 8.2.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `projet_catalogue`
--

-- --------------------------------------------------------

--
-- Structure de la table `jeux`
--

CREATE TABLE `jeux` (
  `id_game` int NOT NULL,
  `title_game` varchar(255) NOT NULL,
  `text_game` text NOT NULL,
  `picture_right` varchar(255) NOT NULL,
  `picture_right_alt` varchar(255) NOT NULL,
  `picture_left` varchar(255) NOT NULL,
  `picture_left_alt` varchar(255) NOT NULL,
  `desc_game` text NOT NULL,
  `trailler` varchar(255) NOT NULL,
  `picture_header` varchar(255) NOT NULL,
  `picture_header_alt` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `jeux`
--

INSERT INTO `jeux` (`id_game`, `title_game`, `text_game`, `picture_right`, `picture_right_alt`, `picture_left`, `picture_left_alt`, `desc_game`, `trailler`, `picture_header`, `picture_header_alt`) VALUES
(60, 'hollow knight', 'Hollow Knight est un jeu classique d\'action et d\'aventure en 2D, qui prend place dans un vaste monde souterrain interconnecté. Explorez un labyrinthe de cavernes, de villes ancestrales et de terres désolées dangereuses\">\">\">', '../img/jeu/x9r60TNvyc4vrquh0qMg.png', 'hollow knight game', '../img/jeu/71UQZy7HEjL._AC_UF1000,1000_QL80_.jpg', 'hollow knight game', 'Hollow Knight est un jeu classique d\'action et d\'aventure en 2D, qui prend place dans un vaste monde souterrain interconnecté. Explorez un labyrinthe de cavernes, de villes ancestrales et de terres désolées dangereuses', 'https://www.youtube.com/embed/nSPJXlYjENE?si=GcfzVZnFWlYe0pIy', '../img/jeu/tumblr_pex178fsYq1x73yfbo8_1280.jpg', 'hollow knight game '),
(61, 'dark souls III', 'L\'Âge du Feu peut être prolongé en se liant au Feu, un rituel dans lequel les grands seigneurs et héros sacrifient leur âme afin de faire perdurer la Première Flamme. Cependant, le Prince Lothric, désigné comme devant se lier au Feu, a abandonné son devoir et choisi d\'observer de loin la mort des flammes\">\">\">', '../img/jeu/tCq4ThJLiWkXhOCpp8O3.jpg', 'dark souls 3 game', '../img/jeu/616p1i6gfxL._AC_UF1000,1000_QL80_.jpg', 'dark souls 3 game', 'L\'Âge du Feu peut être prolongé en se liant au Feu, un rituel dans lequel les grands seigneurs et héros sacrifient leur âme afin de faire perdurer la Première Flamme. Cependant, le Prince Lothric, désigné comme devant se lier au Feu, a abandonné son devoir et choisi d\'observer de loin la mort des flammes', 'https://www.youtube.com/embed/_zDZYrIUgKE?si=uEoFenhmhCP9cEoo', '../img/jeu/2808.jpg', 'dark souls 3 game'),
(64, 'Valorant', 'Valorant est un FPS compétitif développé par Riot Games. Deux équipes de cinq joueurs s\'affrontent sur plusieurs rounds. L\'équipe en Attaque doit poser un Spike (une bombe) sur des sites spécifiques, tandis que l\'équipe en Défense doit l\'empêcher ou le désamorcer.\r\n\r\nChaque joueur choisit un Agent avec des capacités uniques. Les rôles des agents sont :\r\n\r\nDuelists : spécialisés dans l\'attaque et les éliminations.\r\nInitiators : perturbent les défenses ennemies pour créer des ouvertures.\r\nSentinels : protègent les sites et apportent du soutien.\r\nControllers : manipulent le champ de bataille avec des fumées et des murs.\r\nLes joueurs gagnent des crédits en fonction de leur performance (plantation ou désamorçage du Spike, éliminations, etc.) pour acheter des armes, des boucliers et des compétences. La gestion économique est cruciale pour maintenir un avantage sur l\'ennemi.\r\n\r\nLe jeu se déroule sur différentes cartes, chacune avec des configurations uniques et des sites de pose de Spike spécifiques. Les équipes doivent adapter leurs stratégies en fonction de la carte et des agents choisis.\r\n\r\nChaque manche dure 100 secondes, et une partie se joue en 25 manches maximum. Une équipe doit gagner 13 manches pour remporter la partie. Les parties sont intenses et nécessitent une coordination et une stratégie d\'équipe précises.\r\n', '../img/jeu/qDqrV0KSqtVHeTcYnWuc.png', 'valorant game', '../img/jeu/gIMkg7gFQFtHDzzHPdWg.jpg', 'valorant game', 'Valorant est un FPS (First Person Shooter) compétitif édité par Riot Games où deux équipes de cinq joueurs s\'affrontent pendant plusieurs rounds sur des cartes fermées. L\'équipe en Attaque doit poser un Spike (une bombe) sur un des sites d\'explosion donnés. L\'équipe en Défense doit, quant à elle, désamorcer le Spike.', 'https://www.youtube.com/embed/e_E9W2vsRbQ?si=BCU0GAYTkMJR834F', '../img/jeu/QiOpJSWVLA1Tw6OvTnwW.jpg', 'valorant game'),
(65, 'ruined king', 'Ruined King\" est un jeu vidéo développé par Airship Syndicate et édité par Riot Forge, sorti en 2021. C\'est un RPG tactique se déroulant dans l\'univers de League of Legends, célèbre jeu de MOBA. L\'histoire commence après la mort du roi Gangplank de Bilgewater, une île infâme et corrompue. Une malédiction mystérieuse émerge, transformant les morts en êtres hostiles connus sous le nom de revenants.\r\n\r\nLes joueurs incarnent plusieurs champions de League of Legends, dont Miss Fortune, Braum, Illaoi, Pyke, Ahri et Yasuo, chacun avec ses compétences uniques et son style de combat. Ils forment une équipe hétéroclite pour enquêter sur les origines de cette malédiction et restaurer la paix à Bilgewater. Le jeu combine exploration, combat au tour par tour et résolution d\'énigmes dans des environnements détaillés et richement illustrés.\r\n\r\nL\'exploration se déroule sur plusieurs îles, chacune regorgeant de secrets à découvrir et de défis à relever. Les combats tactiques se déroulent au tour par tour, où la stratégie et la coordination des compétences sont essentielles pour vaincre les ennemis variés, y compris des boss redoutables.\r\n\r\nGraphiquement, \"Ruined King\" se distingue par son style visuel dessiné à la main et ses cinématiques immersives qui enrichissent l\'histoire complexe du jeu. Avec une bande-son captivante et une narration immersive, le jeu plonge les joueurs dans un monde sombre et mystérieux, offrant une expérience unique qui ravira à la fois les fans de League of Legends et les nouveaux venus dans l\'univers de Runeterra.', '../img/jeu/bRIMInUuvcXRjoRgyffL.jpg', 'ruined king game', '../img/jeu/zoOQSo8g7Z7q0H39IQgC.png', 'ruined king game', 'Ruined King\" est un RPG tactique se déroulant dans l\'univers de League of Legends, où les joueurs dirigent des champions emblématiques pour enquêter sur une malédiction à Bilgewater. Le jeu combine exploration, combat au tour par tour et résolution d\'énigmes, avec des graphismes dessinés à la main et une narration immersive.', 'https://www.youtube.com/embed/PpRRLYJ5fIQ?si=uldk2VVhVFt6gG2m', '../img/jeu/myv0zSdFQf469KsRfGVY.jpg', 'ruined king game'),
(66, 'pokemon ecarlate et violet', 'Pokémon Écarlate et Violet représentent une nouvelle génération de jeux de rôle Pokémon exclusifs à la Nintendo Switch. Développés par Nintendo, ces titres combinent tradition et innovation en introduisant de nouveaux Pokémon, une région inédite et des mécaniques de jeu revues.\r\n\r\nLes jeux se déroulent dans la région de Carminia, un archipel tropical riche en diversité naturelle et culturelle. Les joueurs commencent leur aventure en choisissant parmi trois Pokémon de départ et explorent une carte détaillée comprenant des environnements variés tels que des jungles luxuriantes, des montagnes escarpées et des villes animées.\r\n\r\nUne des nouveautés notables est le système de capture amélioré, permettant aux joueurs d\'interagir plus activement avec les Pokémon sauvages pour augmenter leurs chances de capture. De plus, les combats ont été enrichis avec de nouvelles attaques et des stratégies avancées.\r\n\r\nL\'histoire principale tourne autour d\'un mystère ancien lié aux légendes locales, mettant en lumière des personnages charismatiques et des énigmes à résoudre tout au long du périple du joueur. Les graphismes sont magnifiés par la puissance de la Nintendo Switch, offrant des animations fluides et des détails visuels saisissants.\r\n\r\nEn résumé, Pokémon Écarlate et Violet visent à séduire à la fois les nouveaux joueurs et les fans de longue date en offrant une expérience riche et immersive tout en conservant l\'essence qui a fait le succès de la franchise Pokémon depuis ses débuts', '../img/jeu/NLprDWLJkNFhHNpQ9rg3.jpg', 'pokemon ecarlate et violet game', '../img/jeu/Ct29Yz62EmE81dgVqmbz.png', 'pokemon ecarlate et violet game', 'Pokémon Écarlate et Violet sont des jeux de rôle développés par Nintendo pour la Nintendo Switch. Ils introduisent de nouveaux Pokémon, des régions inédites et des mécaniques de jeu innovantes, tout en restant fidèles à l\'esprit classique de la franchise', 'https://www.youtube.com/embed/ETAzCS94lrs?si=vlCy31DcyweRnaWx', '../img/jeu/IISZxEZm0ecZ2BoF334L.jpg', 'pokemon ecarlate et violet game'),
(67, 'the last of us part I', 'The Last of Us est un jeu d\'action-aventure acclamé, développé par Naughty Dog exclusivement pour la PlayStation. Situé dans un monde post-apocalyptique ravagé par une pandémie, le jeu suit l\'odyssée de Joel, un trafiquant de marchandises, et Ellie, une adolescente avec un potentiel vital pour l\'humanité.\r\n\r\nL\'histoire commence vingt ans après l\'effondrement de la société moderne. Joel est chargé d\'escorter Ellie à travers les États-Unis, une tâche périlleuse qui les confronte à des hordes de mutants cannibales et à des groupes humains hostiles. Le jeu explore non seulement leur lutte pour la survie mais aussi la construction de leur relation complexe et émotive au fil du voyage.\r\n\r\nLe gameplay combine l\'exploration immersive avec des mécaniques de survie intenses, nécessitant la gestion prudente des ressources limitées. Les combats exigent une approche tactique, souvent favorisant la discrétion et l\'évitement plutôt que l\'affrontement direct.\r\n\r\nGraphiquement impressionnant, The Last of Us est salué pour ses paysages post-apocalyptiques saisissants, ses personnages profondément développés et ses dialogues poignants. La narration captivante et les choix moraux confrontants ajoutent une profondeur émotionnelle et philosophique à l\'expérience globale.\r\n\r\nEn résumé, The Last of Us se distingue comme un chef-d\'œuvre du jeu vidéo, combinant une histoire captivante avec un gameplay innovant et une présentation visuelle impressionnante, offrant aux joueurs une expérience inoubliable dans un monde déchiré par la désolation et l\'humanité en déclin', '../img/jeu/EeKxhVQMt9OzbGxNLsN5.jpg', 'the last of us game', '../img/jeu/r9uEw3lZpfOQkgE5VCcV.jpg', 'the last of us game', 'The Last of Us est un jeu d\'action-aventure développé par Naughty Dog pour PlayStation. Il narre l\'histoire poignante de Joel et Ellie, traversant un monde post-apocalyptique infesté de mutants. Le gameplay allie exploration, survie et combat stratégique', 'https://www.youtube.com/embed/_6v_D3QocIs?si=ovQFiZhICBb91Vd3', '../img/jeu/oqzJyBUJoxGGhxcjxcRV.jpg', 'the last of us game'),
(68, 'elden ring', 'Elden Ring est un jeu d\'action-RPG développé par FromSoftware en collaboration avec George R.R. Martin. Plongé dans un monde fantastique ouvert, les joueurs explorent des terres mythiques, affrontent des ennemis redoutables et découvrent une histoire riche en secrets et en mystères.\">\r\n\r\nL\'histoire se déroule dans le royaume de la Terre Brisée, autrefois dominé par l\'Elden Ring, une force mystique qui maintenait l\'équilibre entre les différentes factions et divinités. Après que l\'Elden Ring a été brisé, le monde a plongé dans le chaos, engendrant des créatures monstrueuses et des conflits sans fin.\r\n\r\nLes joueurs incarnent un personnage personnalisable qui explore librement ce vaste monde, découvrant des donjons, des cités abandonnées et des paysages majestueux, tout en affrontant des ennemis redoutables et en apprenant à maîtriser des compétences et des magies puissantes.\r\n\r\nLe gameplay d\'Elden Ring combine des mécaniques de combat tactiques avec un système de progression basé sur l\'exploration et la découverte. Les choix du joueur influencent non seulement l\'histoire mais aussi le destin des divers personnages rencontrés.\r\n\r\nAvec des visuels impressionnants et une atmosphère dense, Elden Ring promet une expérience immersive et profonde, captivant les joueurs avec une narration complexe et des défis exigeants caractéristiques des œuvres de FromSoftware.\r\n\r\nEn résumé, Elden Ring s\'annonce comme un nouvel opus ambitieux qui mêle la vision de George R.R. Martin à l\'expertise de FromSoftware, promettant une aventure épique et inoubliable dans un univers de fantasy sombre et captivant', '../img/jeu/e3IeFvV7W2mZpO7SbW02.jpg', 'elden ring game', '../img/jeu/xicHVbhkmwPaC1iShiUD.jpg', 'elden ring game', 'Elden Ring est un jeu très attendu d\'action-RPG développé par FromSoftware, connu pour la série Dark Souls, en collaboration avec l\'auteur George R.R. Martin. Situé dans un monde ouvert fantastique et sombre, Elden Ring propose aux joueurs une exploration immersive des terres déchirées par la guerre et le chaos.', 'https://www.youtube.com/embed/M2EZDQ6_jfA?si=9IE4zz-ZfWmoNIxu', '../img/jeu/IzAhzT958p270rQzsdZG.png', 'elden ring game'),
(69, 'Spiderman', '\"Spider-Man\" est un jeu d\'action-aventure développé par Insomniac Games et publié par Sony Interactive Entertainment. Sorti en septembre 2018 sur PlayStation 4, le jeu offre une expérience immersive en mettant les joueurs dans la peau de Peter Parker, alias Spider-Man, dans un environnement de monde ouvert richement détaillé, basé sur la ville de New York.\r\n\r\nLe gameplay se distingue par ses mécaniques de déplacement fluide et acrobatique, permettant aux joueurs de se balancer de gratte-ciel en gratte-ciel avec une grande liberté. Les combats sont dynamiques et variés, mélangeant des attaques au corps à corps, des gadgets innovants et des mouvements spéciaux emblématiques de Spider-Man. Le système de combat rappelle celui de la série \"Batman: Arkham\", avec des enchaînements de coups, des contres et des esquives.\r\n\r\nL\'histoire originale du jeu explore la vie de Peter Parker à un moment où il est déjà un super-héros expérimenté. Il doit faire face à de nombreux ennemis classiques, tels que le Docteur Octopus, le Caïd, et le Vautour, tout en jonglant avec sa vie personnelle et ses relations. Le scénario est captivant et bien écrit, offrant des moments d\'émotion, d\'humour et de tension.\r\n\r\nEn plus de la quête principale, le jeu propose de nombreuses activités secondaires, des défis, et des missions annexes qui enrichissent l\'expérience et permettent de débloquer de nouveaux costumes et capacités pour Spider-Man. Avec ses graphismes époustouflants, son gameplay addictif et son histoire engageante, \"Spider-Man\" est considéré comme l\'un des meilleurs jeux de super-héros jamais réalisés.', '../img/jeu/spid 1.jpg', 'Spiderman', '../img/jeu/xbox 3.jpg', 'Spiderman', '\"Spider-Man\" est un jeu d\'action-aventure développé par Insomniac Games. Le joueur incarne Peter Parker, alias Spider-Man, dans une New York ouverte et détaillée. Le gameplay mêle combats dynamiques, acrobaties aériennes et exploration, tout en suivant une histoire originale et captivante.', 'https://www.youtube.com/embed/q4GdJVvdxss?si=BE4ChiCmDlyT5rdW', '../img/jeu/spid 3.jpg', 'Spiderman'),
(70, 'Grand Theft Auto V', '\"Grand Theft Auto V\" (GTA V) est un jeu d\'action-aventure en monde ouvert développé par Rockstar North et publié par Rockstar Games. Sorti initialement en 2013, il est rapidement devenu l\'un des jeux les plus populaires et influents de tous les temps. L\'histoire se déroule dans la ville fictive de Los Santos, inspirée de Los Angeles, et suit les vies entrecroisées de trois personnages principaux : Michael De Santa, un ancien braqueur de banque en quête de rédemption; Franklin Clinton, un jeune gangster cherchant à sortir des bas-fonds; et Trevor Philips, un ancien pilote militaire et criminel imprévisible.\r\n\r\nLe jeu se distingue par son monde ouvert vaste et détaillé, offrant une liberté sans précédent aux joueurs pour explorer, accomplir des missions, et interagir avec l\'environnement. Les missions vont des braquages de banques aux courses de voitures, en passant par des activités quotidiennes comme le golf et le yoga. GTA V est également connu pour ses mécaniques de jeu innovantes, permettant aux joueurs de basculer entre les trois protagonistes à tout moment, offrant ainsi des perspectives différentes et des stratégies variées pour accomplir les missions.\r\n\r\nLe mode multijoueur en ligne, GTA Online, enrichit l\'expérience en permettant aux joueurs de créer leurs propres personnages et de participer à des activités coopératives ou compétitives avec des millions d\'autres joueurs à travers le monde. Avec ses graphismes impressionnants, son scénario captivant, et ses innombrables possibilités de jeu, GTA V continue d\'être un pilier de l\'industrie vidéoludique.', '../img/jeu/gta 1.jpg', 'Grand Theft Auto V', '../img/jeu/gta 12.jpg', 'Grand Theft Auto V', '\"GTA V\" est un jeu d\'action-aventure en monde ouvert développé par Rockstar Games. Il suit les histoires entrelacées de trois criminels dans la ville fictive de Los Santos. Le gameplay offre des missions variées, du braquage à la conduite, et un mode multijoueur en ligne riche en contenu.', 'https://www.youtube.com/embed/QkkoHAzjnUs?si=3F9eMAhuFkOSDcqz', '../img/jeu/gta 2.jpg', 'Grand Theft Auto V'),
(71, 'Prince of persia', '\r\n\"Prince of Persia\" est un jeu d\'action-aventure révolutionnaire créé par Jordan Mechner et initialement sorti en 1989. Le jeu se déroule dans l\'ancienne Perse, où le joueur incarne un prince anonyme qui doit sauver une princesse emprisonnée par le maléfique vizir Jaffar. Celui-ci a donné à la princesse une heure pour accepter de l\'épouser ou mourir, et c\'est à vous de la sauver avant que le temps ne s\'écoule.\r\n\r\nLe jeu se distingue par ses animations fluides, obtenues grâce à une technique innovante de rotoscopie, où les mouvements réels des acteurs sont capturés et transposés en animation. Cela confère au prince des mouvements réalistes, comme courir, sauter, grimper et se battre avec une grande fluidité.\r\n\r\nLe gameplay se concentre sur l\'agilité et la précision, nécessitant des sauts précis et des réflexes rapides pour éviter des pièges mortels tels que des piques et des lames tranchantes. Les combats à l\'épée ajoutent une autre couche de défi, où le joueur doit maîtriser les attaques et les parades pour vaincre les gardes ennemis.\r\n\r\n\"Prince of Persia\" est également connu pour ses puzzles et ses énigmes, qui exigent des solutions créatives et une exploration attentive des niveaux. Le jeu a été acclamé pour son innovation technique et son gameplay captivant, et il a engendré plusieurs suites et remakes, établissant une franchise durable et influente dans l\'histoire des jeux vidéo.', '../img/jeu/prince-of-persia-1.jpg', 'Prince of persia', '../img/jeu/prince 3.jpg', 'Prince of persia', '\"Prince of Persia\" est un jeu d\'action-aventure créé par Jordan Mechner en 1989. Il se distingue par ses animations fluides et son gameplay basé sur l\'agilité et la résolution d\'énigmes. Le protagoniste doit sauver une princesse en surmontant des pièges et des ennemis dans un palais.', 'https://www.youtube.com/embed/MmX7a_e65uU?si=w2oa6RHmyZmu8cqX', '../img/jeu/prince 2.jpg', 'Prince of persia'),
(72, 'One piece', '\"One Piece: Pirate Warriors 4\" est un jeu d\'action-aventure développé par Omega Force et publié par Bandai Namco Entertainment. Sorti en mars 2020, il s\'inspire de la célèbre série de mangas et d\'anime \"One Piece\" créée par Eiichiro Oda. Ce jeu est le quatrième volet de la série \"Pirate Warriors\", mélangeant les éléments classiques du genre musou (combat contre des hordes d\'ennemis) avec l\'univers riche et coloré de \"One Piece\".\r\n\r\nLe jeu propose une vaste sélection de personnages jouables, chacun avec ses propres mouvements et capacités uniques, tirés directement de l\'œuvre originale. Les joueurs peuvent incarner Luffy et son équipage, mais aussi d\'autres personnages emblématiques tels que Trafalgar Law, Big Mom, et Kaido. Le gameplay dynamique permet d\'exécuter des combos spectaculaires et de dévaster des armées entières d\'ennemis.\r\n\r\n\"Pirate Warriors 4\" couvre plusieurs arcs narratifs de la série, allant de l\'arc d\'Alabasta jusqu\'à Wano, avec des ajouts originaux pour enrichir l\'expérience de jeu. Les graphismes sont fidèles au style visuel de l\'anime, et les environnements destructibles ajoutent une dimension supplémentaire aux batailles.\r\n\r\nLe mode multijoueur permet également aux fans de coopérer en ligne pour affronter les défis ensemble, renforçant ainsi l\'aspect communautaire du jeu. Avec son mélange de fidélité à la source et de gameplay engageant, \"One Piece: Pirate Warriors 4\" est une expérience incontournable pour les fans de la série et les amateurs de jeux d\'action.', '../img/jeu/switch 11.jpg', 'One piece', '../img/jeu/one-piece-1.jpg', 'One piece', '\"One Piece: Pirate Warriors 4\" est un jeu d\'action-aventure basé sur le manga \"One Piece\". Développé par Omega Force et Koei Tecmo, il offre des combats dynamiques contre des hordes d\'ennemis, avec des personnages et arcs narratifs fidèlement recréés. Le gameplay est inspiré de la série \"Dynasty Warriors\".', 'https://www.youtube.com/embed/FzIkh-98_hk?si=nmthj7QSyQRS1Uk_', '../img/jeu/one-piece-pirate-2.jpg', 'One piece'),
(75, 'Overwatch 2', '\"Overwatch\" est un jeu de tir en équipe créé par Blizzard Entertainment, sorti en 2016. Il se distingue par son gameplay dynamique et stratégique mettant en vedette une variété de héros aux capacités distinctes. Chaque joueur choisit un personnage parmi une large sélection, chaque héros ayant des compétences uniques qui contribuent à différents rôles comme attaquant, défenseur, tank ou soutien.\r\n\r\nLe jeu se déroule dans un futur proche où des équipes de six joueurs s\'affrontent sur diverses cartes à travers le monde. Les modes de jeu incluent la capture de points, le transport de charges et la défense de zones spécifiques, chaque mission nécessitant une coordination d\'équipe et une stratégie pour réussir.\r\n\r\nL\'aspect stratégique d\'\"Overwatch\" repose sur la combinaison des compétences des différents héros pour créer des synergies efficaces. Par exemple, certains personnages peuvent soigner leurs coéquipiers, renforcer leur défense ou causer des dégâts massifs à l\'ennemi. Les mises à jour régulières introduisent de nouveaux héros, cartes et ajustements d\'équilibrage pour maintenir le jeu frais et équilibré.\r\n\r\nEn plus du gameplay compétitif, \"Overwatch\" offre une riche lore avec des animations cinématiques, des comics et des événements spéciaux qui enrichissent l\'univers et approfondissent les histoires des personnages. Le jeu est également apprécié pour ses graphismes colorés, son design de niveau détaillé et son engagement envers une communauté mondiale active, faisant d\'\"Overwatch\" un titre incontournable dans le domaine des jeux de tir en équipe.', '../img/jeu/fePK5O8oD5JZGzbT5aIw.jpg', 'Overwatch 2', '../img/jeu/SRsrqNhkAxOI4vfX1wSB.jpg', 'Overwatch 2', '\"Overwatch\" est un jeu de tir en équipe développé par Blizzard Entertainment. Il met en scène des héros aux compétences uniques dans des affrontements multijoueurs rapides et stratégiques. Les joueurs doivent coopérer pour accomplir des objectifs variés sur des cartes diversifiées, alliant action dynamique et gameplay compétitif.', 'https://www.youtube.com/embed/pyS3vmnWTyU?si=1nb8tH95bpw-9hCd', '../img/jeu/hLA7MXZjxKSPCpUDaOpy.jpg', 'Overwatch 2'),
(76, 'Minecraft', '\"Minecraft\" est un phénomène mondial de jeu de survie et de construction développé par Mojang Studios. Lancé en 2011, il offre une expérience immersive où les joueurs explorent un vaste monde ouvert généré de manière procédurale, composé de blocs pixelisés. Le jeu permet aux joueurs de collecter des ressources naturelles telles que le bois, la pierre et le minerai, puis d\'utiliser ces matériaux pour construire des structures complexes, des villes, voire des mondes entiers.\r\n\r\nLe gameplay de \"Minecraft\" est centré sur la créativité, l\'exploration et la survie. Les joueurs doivent gérer leur santé et leur nourriture tout en se défendant contre des créatures hostiles telles que des zombies, des squelettes et des araignées. Le jour, ils explorent, minent et construisent, tandis que la nuit apporte des dangers supplémentaires, incitant à la construction de refuges et à la création d\'armes et d\'armures pour se protéger.\r\n\r\nEn plus du mode solo, \"Minecraft\" propose un mode multijoueur où les joueurs peuvent collaborer pour construire, explorer et même combattre ensemble. Les possibilités sont presque illimitées grâce à la créativité des joueurs et aux mods, qui permettent de modifier le jeu pour ajouter de nouvelles fonctionnalités, de nouveaux blocs, ou même de nouveaux modes de jeu.\r\n\r\n\"Minecraft\" est acclamé pour son gameplay simple mais profond, sa communauté dévouée et ses mises à jour régulières qui enrichissent continuellement l\'expérience. Il a captivé des millions de joueurs à travers le monde et continue d\'évoluer comme une plateforme de jeu influente et innovante.', '../img/jeu/L3hBovjJZAH6EkcEeRK5.jpg', 'Minecraft', '../img/jeu/aABSfgFOeRW7qfepCtCZ.jpg', 'Minecraft', '\"Minecraft\" est un jeu de construction et d\'aventure bac à sable, créé par Mojang Studios. Les joueurs explorent un monde ouvert généré procéduralement, extrayant des ressources, fabriquant des outils et construisant des structures. Le gameplay encourage la créativité, l\'exploration et la survie dans un environnement pixelisé aux possibilités infinies.', 'https://www.youtube.com/embed/MmB9b5njVbA?si=GE6V5fWhlfAepGGT', '../img/jeu/c67okZMlCvIcxo7DJq6s.jpg', 'Minecraft'),
(77, 'Splatoon 3', '\"Splatoon 3\" est le troisième volet de la franchise de jeu de tir multijoueur développée par Nintendo, où les joueurs incarnent des Inklings ou des Octalings, des personnages mi-humains mi-creatures marines capables de se transformer en forme liquide pour nager à travers l\'encre colorée de leur équipe.\r\n\r\nLe jeu se déroule dans un monde post-apocalyptique où les Inklings et les Octalings s\'affrontent dans des batailles énergiques pour le contrôle territorial. Le gameplay combine action rapide et stratégie, avec une variété d\'armes spéciales, de gadgets et de compétences à maîtriser. Les modes de jeu incluent des classiques comme la \"Zone splatting\" où les équipes tentent de couvrir le plus de terrain avec leur encre colorée, ainsi que de nouveaux modes et défis qui testent la coordination et les compétences des joueurs.\r\n\r\nLes personnalisations sont au cœur de \"Splatoon 3\", avec la possibilité de personnaliser l\'apparence de son Inkling ou Octaling, ainsi que de choisir parmi une gamme d\'armes spéciales et de vêtements pour améliorer les capacités en combat. Le jeu encourage également la coopération grâce à des batailles en équipe, où la communication et la coordination sont essentielles pour remporter la victoire.\r\n\r\nAvec son style visuel vibrant, sa musique entraînante et ses mécaniques de jeu innovantes, \"Splatoon 3\" promet une expérience rafraîchissante et captivante pour les fans de jeux de tir multijoueur et pour ceux qui découvrent la série pour la première fois.', '../img/jeu/EcuEuQelV4RXo5nq3Y9J.jpg', 'Splatoon 3', '../img/jeu/qgNLfJ4Z2NAChUXCJeJt.jpg', 'Splatoon 3', '\"Splatoon 3\" est un jeu de tir multijoueur développé par Nintendo. Les joueurs contrôlent des Inklings ou des Octalings pour participer à des combats colorés en équipe. Le gameplay combine action dynamique et stratégie, avec des armes variées et des modes de jeu comme la zone splatting et la bataille territoriale.', 'https://www.youtube.com/embed/xcri49UjckE?si=WyZzJTxYRqm9ogDr', '../img/jeu/jsVGfwUSOG0ButzCrNCT.jpg', 'Splatoon 3'),
(78, 'Luigi\'s Mansion 3', '\r\n\"Luigi\'s Mansion 3\" est un jeu d\'aventure développé par Next Level Games et publié par Nintendo, exclusivement pour la Nintendo Switch. Dans ce troisième volet de la série \"Luigi\'s Mansion\", les joueurs incarnent Luigi qui, accompagné de son fidèle Poltergust G-00 (un aspirateur à fantômes), explore un hôtel luxueux hanté appelé l\'Hôtel Last Resort.\r\n\r\nL\'histoire démarre lorsque Luigi et ses amis sont invités à passer des vacances à l\'hôtel, mais découvrent rapidement que c\'est un piège orchestré par le Roi Boo. Luigi doit alors sauver ses amis capturés par les fantômes et déjouer les plans maléfiques du Roi Boo.\r\n\r\nLe gameplay de \"Luigi\'s Mansion 3\" combine exploration, résolution d\'énigmes et combat contre les fantômes. Avec le Poltergust G-00, les joueurs aspirent les fantômes, résolvent des puzzles environnementaux et utilisent diverses capacités pour progresser à travers les différents étages de l\'hôtel. Chaque étage est unique, offrant des thèmes et des défis variés, allant des suites thématiques aux salles de spectacle hantées.\r\n\r\nLe jeu met également en avant la coopération avec Gooigi, une version gélatineuse de Luigi contrôlée par le joueur ou par un ami en mode coopératif local. Gooigi peut passer à travers les grilles et obstacles, apportant une dimension stratégique supplémentaire aux énigmes et aux combats.\r\n\r\nAvec ses graphismes détaillés et colorés, son humour charmant et son gameplay captivant, \"Luigi\'s Mansion 3\" est une aventure fantaisiste qui séduit les fans de tous âges et continue d\'enrichir l\'univers charmant de Luigi et de ses chasses aux fantômes.', '../img/jeu/5M9yPztgfvUFU5o7tlHc.jpg', 'Luigi\'s Mansion 3', '../img/jeu/ENPjiXuQtJcdcNxccI23.jpg', 'Luigi\'s Mansion 3', '\r\n\"Luigi\'s Mansion 3\" est un jeu d\'aventure développé par Next Level Games pour Nintendo Switch. Luigi explore un hôtel hanté pour sauver ses amis capturés par des fantômes. Utilisant un aspirateur à fantômes, le Poltergust G-00, il résout des énigmes et affronte des boss pour progresser dans le jeu.', 'https://www.youtube.com/embed/OYhTRG8k3-4?si=3kqTu7KmMOiWeZ90', '../img/jeu/pn5a8YyJAydWYjlzP6Fl.jpg', 'Luigi\'s Mansion 3'),
(79, 'Hello Neigbhor 2', '\"Hello Neighbor 2\" est un jeu d\'horreur et d\'aventure développé par Dynamic Pixels et édité par tinyBuild. C\'est la suite du jeu original \"Hello Neighbor\", où les joueurs explorent une maison voisine pour découvrir les secrets sinistres de leur voisin. Dans cette suite, l\'intrigue se déroule dans une ville en constante évolution appelée Raven Brooks.\r\n\r\nLe jeu met en scène une intelligence artificielle avancée pour le voisin, qui apprend des actions des joueurs et adapte ses comportements en conséquence, rendant chaque expérience unique et imprévisible. Les joueurs doivent utiliser la ruse et la réflexion stratégique pour éviter les pièges du voisin tout en cherchant des indices et des objets nécessaires pour progresser dans l\'histoire.\r\n\r\nL\'environnement ouvert de Raven Brooks permet une exploration libre, où les joueurs peuvent découvrir de nouveaux quartiers, des bâtiments abandonnés et des secrets cachés. Le gameplay se concentre sur la résolution d\'énigmes complexes et la collecte d\'indices dispersés dans la ville pour démêler le mystère du voisin et de ses expériences troublantes.\r\n\r\n\"Hello Neighbor 2\" promet une atmosphère immersive avec des graphismes améliorés et une bande-son immersive, amplifiant le sentiment d\'angoisse et de suspense tout au long du jeu. Le titre vise à offrir une expérience d\'horreur psychologique captivante où la tension monte à mesure que les joueurs explorent les recoins sombres de Raven Brooks pour percer les mystères du voisin.', '../img/jeu/0PlKm08rpmydEp2j5dmc.jpg', 'Hello Neigbhor 2', '../img/jeu/Tny1OEbcLL9NAdmRsrCn.jpg', 'Hello Neigbhor 2', '\"Hello Neighbor 2\" est un jeu d\'horreur et d\'aventure où les joueurs explorent la ville de Raven Brooks pour découvrir les secrets de leur voisin sinistre. Utilisant l\'intelligence artificielle avancée, le voisin s\'adapte aux actions des joueurs, créant une expérience unique à chaque partie avec des puzzles et des dangers imprévisibles.', 'https://www.youtube.com/embed/kotJEIahGdQ?si=XYZSbs1-s_V3feVa', '../img/jeu/meKuvhmoCZ8TwUXTAvzc.jpg', 'Hello Neigbhor 2'),
(80, 'Assassin\'s Creed', '\"Assassin\'s Creed\" est une franchise de jeux d\'action-aventure développée par Ubisoft. Chaque jeu transporte les joueurs à travers des époques historiques variées, depuis l\'ère des croisades jusqu\'à l\'Égypte ancienne et au-delà. Les joueurs incarnent généralement des assassins, membres d\'une société secrète luttant contre les Templiers, leurs ennemis jurés.\r\n\r\nLe gameplay combine exploration en monde ouvert, infiltration et combats fluides. Les joueurs utilisent le parkour pour se déplacer librement à travers les villes historiques comme Jérusalem, Florence, Paris et Londres, tout en accomplissant des missions variées qui vont de l\'assassinat de cibles importantes à la collecte d\'informations cruciales.\r\n\r\nChaque jeu de la série propose une histoire riche et complexe, entrelaçant des éléments historiques avec une intrigue fictionnelle impliquant des artefacts anciens et des conspirations secrètes. Les protagonistes principaux, tels qu\'Altair, Ezio Auditore, Connor Kenway, Edward Kenway, Arno Dorian, Bayek, et bien d\'autres, ont chacun leur propre voyage personnel et leur rôle crucial dans la lutte contre les Templiers à travers les siècles.\r\n\r\nLa franchise est acclamée pour son attention aux détails historiques, ses graphismes immersifs et son gameplay varié qui permet aux joueurs de choisir leur approche pour chaque mission. Elle a élargi son univers à travers des jeux, des romans, des bandes dessinées et même des adaptations cinématographiques, devenant une référence majeure dans l\'industrie du jeu vidéo.', '../img/jeu/VUV0OJmAAzHXkfJfOm4O.jpg', 'Assassin\'s Creed', '../img/jeu/hJVa2GE7tbyUQYdjK8rF.jpg', 'Assassin\'s Creed', '\"Assassin\'s Creed\" est une série de jeux d\'action-aventure d\'Ubisoft. Les joueurs incarnent des assassins à travers différentes époques historiques, accomplissant des missions d\'infiltration, d\'assassinat et d\'exploration. Le gameplay combine combat fluide, parkour et narration riche, explorant des conflits ancestraux entre les Assassins et les Templiers.', 'https://www.youtube.com/embed/S7HNwwXxI9U?si=21PCEctENuCNN7pG', '../img/jeu/JMPQ87ossoiNw1oIRJ5l.jpg', 'Assassin\'s Creed');

-- --------------------------------------------------------

--
-- Structure de la table `plateforme`
--

CREATE TABLE `plateforme` (
  `id_plateforme` int NOT NULL,
  `id_game` int NOT NULL,
  `title_game` varchar(255) NOT NULL,
  `pc` tinyint(1) NOT NULL,
  `playstation` tinyint(1) NOT NULL,
  `xbox` tinyint(1) NOT NULL,
  `switch` tinyint(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `plateforme`
--

INSERT INTO `plateforme` (`id_plateforme`, `id_game`, `title_game`, `pc`, `playstation`, `xbox`, `switch`) VALUES
(21, 60, 'hollow knight', 1, 1, 1, 1),
(22, 61, 'dark souls 3', 1, 1, 1, 0),
(25, 64, 'Valorant', 1, 0, 0, 0),
(26, 65, 'ruined king', 1, 1, 1, 1),
(27, 66, 'pokemon ecarlate et violet', 0, 0, 0, 1),
(28, 67, 'the last of us part I', 1, 1, 0, 0),
(29, 68, 'elden ring', 1, 1, 1, 0),
(30, 69, '8', 1, 1, 1, 0),
(31, 70, '9', 1, 1, 1, 0),
(32, 71, '10', 1, 1, 1, 1),
(33, 72, '11', 1, 1, 1, 1),
(36, 75, 'Overwatch 2', 1, 1, 1, 1),
(37, 76, 'Minecraft', 1, 1, 1, 1),
(38, 77, 'Splatoon 3', 0, 0, 0, 1),
(39, 78, 'Luigi\'s Mansion 3', 0, 0, 0, 1),
(40, 79, 'Hello Neigbhor 2', 1, 1, 1, 1),
(41, 80, 'Assassin\'s Creed', 1, 1, 1, 0);

-- --------------------------------------------------------

--
-- Structure de la table `users`
--

CREATE TABLE `users` (
  `id` int NOT NULL,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `pass` varchar(255) NOT NULL,
  `roles` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Déchargement des données de la table `users`
--

INSERT INTO `users` (`id`, `username`, `email`, `pass`, `roles`) VALUES
(3, 'test', 'test@test.test', '$argon2id$v=19$m=65536,t=4,p=1$M0lrV0pZV0szZUtGTXFMVw$woSbo1VeZM32LbI1FZzV/2yYrFoLDLpKPltM9AvzXhs', 'ROLE_USER'),
(4, 'test2', 'test2@gmail.com', '$argon2id$v=19$m=65536,t=4,p=1$dDVpeE9vWXpCdHlmdURpNQ$m2ufAKKG3bG+nIcrW2C+o1+CBwqoBfjQFaK5KJLqito', 'ROLE_USER'),
(5, 'jonathan', 'jonathan@gmail.com', '$argon2id$v=19$m=65536,t=4,p=1$UUJkTHJRaTdXL09qMmpEZA$46t1kjaNuShxcQmzVgSEKqit3yzk8rwGXUItvMDG+sw', 'ROLE_ADMIN'),
(7, 'Léa', 'online@gmail.com', '$argon2id$v=19$m=65536,t=4,p=1$ek9ia2w2ZU9NSVFESy42Wg$Qw45J+xWq3ZTOdvTwarJ/WXm1HF4Pxu+I4GmWJq56dg', 'ROLE_ADMIN');

--
-- Index pour les tables déchargées
--

--
-- Index pour la table `jeux`
--
ALTER TABLE `jeux`
  ADD PRIMARY KEY (`id_game`);

--
-- Index pour la table `plateforme`
--
ALTER TABLE `plateforme`
  ADD PRIMARY KEY (`id_plateforme`);

--
-- Index pour la table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pour les tables déchargées
--

--
-- AUTO_INCREMENT pour la table `jeux`
--
ALTER TABLE `jeux`
  MODIFY `id_game` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=81;

--
-- AUTO_INCREMENT pour la table `plateforme`
--
ALTER TABLE `plateforme`
  MODIFY `id_plateforme` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- AUTO_INCREMENT pour la table `users`
--
ALTER TABLE `users`
  MODIFY `id` int NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
